CREATE DATABASE TheNerdHerd

CREATE TABLE Locations(
Id INT NOT NULL IDENTITY,
Latitude FLOAT,
Longitude FLOAT,
CONSTRAINT PK_Locations PRIMARY KEY(Id)
)

CREATE TABLE Credentials(
Id INT NOT NULL IDENTITY,
Email VARCHAR(30),
Password VARCHAR(20),
CONSTRAINT PK_Credentials PRIMARY KEY(Id)
)

CREATE TABLE Users(
Id INT NOT NULL IDENTITY,
Nickname VARCHAR(25),
Gender CHAR(1),
Age INT,
LocationId INT,
CredentialId INT UNIQUE,
CONSTRAINT PK_Users PRIMARY KEY(Id),
CONSTRAINT FK_Users_Locations FOREIGN KEY (LocationId)
REFERENCES Locations(Id),
CONSTRAINT FK_Users_Credentials FOREIGN KEY (CredentialId)
REFERENCES Credentials(Id)
)

CREATE TABLE Chats(
Id INT NOT NULL IDENTITY,
Title VARCHAR(20),
StartDate DATE,
IsActive BIT,
CONSTRAINT PK_Chats PRIMARY KEY(Id)
)

CREATE TABLE Messages(
Id INT NOT NULL IDENTITY,
Content VARCHAR(200),
SentOn DATE,
ChatId INT,
UserId INT,
Constraint PK_Messages PRIMARY KEY(Id),
CONSTRAINT FK_Messages_Chats FOREIGN KEY (ChatId)
REFERENCES Chats(Id),
CONSTRAINT FK_Messages_Users FOREIGN KEY (UserId)
REFERENCES Users(Id)
)

CREATE TABLE UsersChats(
UserId INT NOT NULL,
ChatId INT NOT NULL,
CONSTRAINT PK_Users_Chats PRIMARY KEY(ChatId, UserId),
CONSTRAINT FK_UserId FOREIGN KEY(UserId)
REFERENCES Users(Id),
CONSTRAINT FK_ChatId FOREIGN KEY(ChatId)
REFERENCES Chats(Id)
)