CREATE TABLE Students(
StudentID INT NOT NULL IDENTITY(1,1),
Name VARCHAR(50) NOT NULL,
CONSTRAINT PK_Students PRIMARY KEY(StudentID)
)

CREATE TABLE Exams(
ExamID INT NOT NULL IDENTITY(101,1),
Name VARCHAR(50) NOT NULL,
CONSTRAINT PK_Exams PRIMARY KEY(ExamID)
)

CREATE TABLE StudentsExams(
StudentID INT NOT NULL,
ExamID  INT NOT NULL,
CONSTRAINT PK_Students_Exams PRIMARY KEY(StudentID, ExamID),
CONSTRAINT FK_StudentID FOREIGN KEY(StudentID)
REFERENCES Students(StudentID),
CONSTRAINT FK_ExamID FOREIGN KEY(ExamID)
REFERENCES Exams(ExamID)
)

